In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn import datasets
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
from sklearn.metrics import confusion_matrix 

In [2]:
iris_data = datasets.load_iris()

In [3]:
iris = pd.DataFrame(iris_data.data, columns=iris_data.feature_names)
iris['target'] = iris_data.target

In [4]:
# Input Data 
x = iris_data.data 
   
# Output Data 
y = iris_data.target 

xtrain, xtest, ytrain, ytest = train_test_split(x, y, test_size =0.2, 
                                                    random_state = 0) 
   
print("xtrain shape : ", xtrain.shape) 
print("xtest shape  : ", xtest.shape) 
print("ytrain shape : ", ytrain.shape) 
print("ytest shape  : ", ytest.shape) 

xtrain shape :  (120, 4)
xtest shape  :  (30, 4)
ytrain shape :  (120,)
ytest shape  :  (30,)


In [5]:
# Fitting Multi Linear regression model to training model 
lr =  LogisticRegression()
lr.fit(xtrain, ytrain)

# predicting the test set results 
y_pred = lr.predict(xtest) 

/home/adarsh/.local/lib/python3.7/site-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


In [6]:
print('Accuracy score: ', format(accuracy_score(ytest, y_pred)))
print('Precision score: ', format(precision_score(ytest, y_pred, average='micro')))
print('Recall score: ', format(recall_score(ytest, y_pred, average='micro')))
print('F1 score: ', format(f1_score(ytest, y_pred, average='micro')))
print('\nConfusion Matrix :\n', confusion_matrix(ytest, y_pred)) 

Accuracy score:  1.0
Precision score:  1.0
Recall score:  1.0
F1 score:  1.0

Confusion Matrix :
 [[11  0  0]
 [ 0 13  0]
 [ 0  0  6]]


# MLP

In [ ]:
from sklearn.neural_network import MLPClassifier
x_train,x_test,y_train,y_test = train_test_split(data1, y ,test_size = 0.3, random_state = 99)
print(x_train.shape)
print(y_train.shape)
print(x_test.shape)
print(y_test.shape)
model = MLPClassifier(solver='sgd', alpha= 0 ,hidden_layer_sizes=(13,5),random_state=1).fit(data1,y)